projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      # codegen:
      #   - generator: typegen
      #     language: typescript
      #     input: "{binding,prisma}/*.ts"
      #     output:
      #       typings: typings.ts
      #   - generator: prisma-binding
      #     language: typescript 
      #     input: schema.graphql
      #     output:
      #       binding: prisma/index.ts