projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  database:
    schemaPath: prisma/generated/prisma.graphql
    extensions:
      prisma: prisma.yml
      # codegen:
      #   - generator: typegen
      #     language: typescript
      #     input: "{binding,prisma}/*.ts"
      #     output:
      #       typings: typings.ts
      codegen:
        - generator: prisma-binding
          language: typescript 
          # input: src/schema.graphql
          output:
            binding: ../prisma/generated/index.ts
